#Local
spring:
  config:
    activate:
      on-profile: omo-dev

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: Ujv8d1zNsQxMuDIeGtgJ
            client-secret: jI2dC4GwWO
            scope:
              - email
            redirect-uri: http://localhost:8080/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  toekn-issuer: omo.depromeet.com
  token-name: omo-app-jwt
  secret: Aa1234567890!@#
  expire-time: 300 #sec

test-page:
  entry: /loginTest.html